config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "picto_speak", to: "picto_speak#home", as: :picto_speak
  post "picto_speak", to: "picto_speak#execute"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/picto_speak_controller.rb
class PictoSpeakController < ApplicationController
  def home
  end

  def execute
    service = ActiveStorage::Blob.service
    service.upload(params['picture'].original_filename, params['picture'])

    base64_image = Base64.encode64(File.read(params['picture'].tempfile))

    messages = [
      { "type": "text", "text": "What’s in this image?"},
      { "type": "image_url",
        "image_url": {
          "url": "data:image/jpeg;base64,#{base64_image}",
        },
      }
    ]
    client = OpenAI::Client.new
    response = client.chat(
        parameters: {
            model: "gpt-4-vision-preview", # Required.
            messages: [{ role: "user", content: messages}], # Required.
        })


    text =  response.dig("choices", 0, "message", "content")

    response = client.audio.speech(
      parameters: {
        model: "tts-1",
        input: text,
        voice: "nova"
      }
    )

    # mp3_name = SecureRandom.hex + '.mp3'
    # service.upload(mp3_name, StringIO.new(response))
    # puts "wrote to #{mp3_name}"

    # send_data response, filename: 'preview.mp3', type: 'audio/mp3', disposition: 'inline'

    # file_path = Rails.root.join('demo.mp3')
    # response = File.binread(file_path)

    encoded_audio_data = Base64.strict_encode64(response)
    render turbo_stream: turbo_stream.replace('audio_container', partial: 'audio_player', locals: { audio_data: encoded_audio_data })
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RailsAiPlayground</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/picto_speak/_audio_player.html.erb
<div id="audio_container">
  <script>
    (function() {
      var audioData = "<%= audio_data %>";

      console.log('Audio data loaded');

      // Check if audioData is valid
      if (!audioData) {
        console.error('No audio data available');
        return;
      }

      var decodedData = atob(audioData);
      var byteArray = new Uint8Array(decodedData.split('').map(char => char.charCodeAt(0)));
      var blob = new Blob([byteArray], { type: 'audio/mp3' });

      // var blob = new Blob([audioData], { type: 'audio/mp3' });
      var url = URL.createObjectURL(blob);
      var audio = new Audio(url);

      console.log('Audio object created');

      // Error event listener
      audio.onerror = function(event) {
        console.error('Error in audio playback', event);
      };

      // Handle play promise
      audio.play().then(function() {
        console.log('Audio playback started successfully');
      }).catch(function(error) {
        console.error('Error occurred during audio playback', error);
      });
    })();
  </script>
</div>

app/views/picto_speak/home.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold text-body-emphasis">Picto Speak</h1>
  <br/><br/>

  <div class="col-lg-6 mx-auto">
    <%= form_with url: picto_speak_path, method: :post do |form| %>
      <%= form.file_field :picture, accept: 'image/png, image/jpeg', required: true %>
      <%= form.submit "Process" %>
    <% end %>
  </div>

  <div id="audio_container">
  </div>
</div>

app/views/projects/index.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold text-body-emphasis">Projects</h1>
  <br/><br/>

  <div class="col-lg-6 mx-auto">
  <div class="list-group">
    <%= link_to "Picto Speak (OpenAI Vision + TTS)", picto_speak_path, class: "list-group-item list-group-item-action" %>
  </ul>
  </div>
</div>